version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: rails s -p 3000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/src:cached
    depends_on:
      - db
    privileged: true
    environment:
      - ACTIVERECORD_UNITTEST_HOST=db
  db:
    image: microsoft/mssql-server-linux
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd!
